logoText = "ä¸–ç•Œä¸€ç•ªã®é¸½ç‹"
logoType = "short" # long, short
description = "ä¸€åªé¸½å­çš„ç¢ç¢å¿µ"
custom_css = []
custom_js = []
useFaviconGenerator = true # https://www.favicon-generator.org/
meta_image = ""
themecolor = ""

themeOptions = ["dark", "light", "hacker", "solarized", "kimbie"]
notAllowedTypesInHome = ["contact", "talks", "about", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInHomeSidebar = ["about", "archive", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInArchive = ["about", "talks", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInHomeFeed = ["about", "archive", "contact", "talks", "showcase", "publication", "presentation", "resume", "gallery"]

viewportSize = "normal" # widest, wider, wide, normal, narrow
enableUiAnimation = true
hideSingleContentsWhenJSDisabled = false
enablePinnedPosts = true
minItemsToShowInTagCloud = 1 # Minimum items to show in tag cloud

# appbar
enableAppbarSearchIcon = true
enableAppbarLangIcon = false

# header
homeHeaderType = "text" # text, img, slide, typewriter
hideHomeHeaderWhenMobile = false

# menu
showMobileMenuTerms = ["tags", "categories", "series"]

# search
enableSearch = true
enableSearchHighlight = true
searchResultPosition = "main" # side, main
searchContent = true # include content to search index
searchDistance = 100 # fuse option
searchThreshold = 0.4 # 0.0: exact match, 1.0: any match

# body
enableBreadcrumb = true
enableGoToTop = true
enableWhoami = true
summaryShape = "classic" # card, classic, compact
archiveGroupByDate = "2006" # "2006-01": group by month, "2006": group by year
archivePaginate = 13
paginateWindow = 1
talksPaginate = 5
talksGroupByDate = "2006"
pubPaginate = 20
writtenTimeIcon = "ğŸ“…"
modifiedTimeIcon = "ğŸ“"
readingTimeIcon = "â˜•"
authorIcon = "âœï¸"
pagePvIcon = "ğŸ‘€"
pinIcon = "ğŸ“Œ"
tagIcon = "ğŸ·ï¸"
publicationIcon = "ğŸ“š"
typeIcon = "ğŸ¯"

# whoami
myname = "Roelxy"
email = "Avazoie@keemail.me"
whoami = "æ–°ä¸–çºªæ‘¸é±¼æˆ˜å£«"
bioImageUrl = "https://im.tantalum.life/accounts/avatars/000/000/034/static/98f3ddae475aa626.png"
useGravatar = false
location = "Oasis, Galaxy"
organization = "Hugo"
link = "https://tantalum.life/"

# sidebar
enableBio = true
enableBioImage = true
enableSidebar = true
enableSidebarTags = true
enableSidebarSeries = true
enableSidebarCategories = true
enableHomeSidebarTitles = true
enableListSidebarTitles = true
enableToc = true
hideToc = false
tocFolding = true
tocPosition = "inner" # inner, outer
enableTocSwitch = true
itemsPerCategory = 5
sidebarPosition = "right"
tocLevels = ["h2", "h3", "h4"]
enableSidebarPostsByOrder = false

# footer
showPoweredBy = true
showFeedLinks = true
showSocialLinks = true
enableLangChange = true
enableThemeChange = true

# service
googleTagManager = "" # GTM-XXXXXX
baiduAnalytics = ""
enableBusuanzi = false
busuanziSiteUV = true
busuanziSitePV = true
busuanziPagePV = true

# rss
updatePeriod = "" # Possible values: 'hourly', 'daily', 'weekly', 'monthly', or 'yearly'.
updateFrequency = ""
fullContents = false

# comment
enableComment = true
disqus_shortname = ""
commento = false

[telegram]
  enable = false
  siteId = ""
  dataLimit = 5

[gitment]          # Gitment is a comment system based on GitHub issues. see https://github.com/imsun/gitment
  owner = ""              # Your GitHub ID
  repo = ""               # The repo to store comments
  clientId = ""           # Your client ID
  clientSecret = ""       # Your client secret

[utterances]       # https://utteranc.es/
  owner = ""              # Your GitHub ID
  repo = ""               # The repo to store comments

[gitalk]           # Gitalk is a comment system based on GitHub issues. see https://github.com/gitalk/gitalk
  owner = ""              # Your GitHub ID
  repo = ""               # The repo to store comments
  clientId = ""           # Your client ID
  clientSecret = ""       # Your client secret

# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[valine]
  enable = false
  appId = 'ä½ çš„appId'
  appKey = 'ä½ çš„appKey'
  notify = false  # mail notifier , https://github.com/xCss/Valine/wiki
  verify = false # Verification code
  avatar = 'mm' 
  placeholder = 'è¯´ç‚¹ä»€ä¹ˆå§...'
  visitor = false

## Waline
    enableWaline = true
    walineServerURL = "https://comment.tantalum.life/"
    walinePlaceholder = "Avazoie@keemail.me"
    walineAvatar = "mp"
    walineMeta = ["nick", "mail", "link"]
    walinePageSize = 10
    walineLang = "zh-CN"
    walineHighlight = true
    walineAvatarCDN = "https://cdn.v2ex.com/gravatar/"
    walineRequiredFields = ["nick", "mail"]
    # è¯´æ˜ï¼šhttps://waline.js.org/


[changyan]
  changyanAppid = ""        # Changyan app id             # ç•…è¨€
  changyanAppkey = ""       # Changyan app key

[livere]
  livereUID = ""            # LiveRe UID                  # æ¥å¿…åŠ›

# Isso: https://posativ.org/isso/
[isso]
  enable = false
  scriptSrc = "" # "https://isso.example.com/js/embed.min.js"
  dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

[socialOptions]
  email = "mailto:Avazoie@keemail.me"
  phone = ""
  facebook = ""
  twitter = ""
  github = "https://github.com/MicroSic"
  stack-overflow = ""
  instagram = ""
  google-plus = ""
  youtube = ""
  medium = ""
  tumblr = ""
  linkedin = ""
  pinterest = ""
  stack-exchange = ""
  telegram = ""
  steam = ""
  weibo = ""
  douban = ""
  csdn = ""
  gitlab = ""
  mastodon = "https://toot.tantalum.life/@Zokiio"
  jianshu = ""
  zhihu = ""
  signal = ""
  whatsapp = ""
  matrix = "@avazoie:o3o.cafe"
  xmpp = ""
  dev-to = ""
  gitea = ""
  google-scholar = ""

[donationOptions]
  enable = false
  alipay = "" 
  wechat = ""
  paypal = ""
  patreon = ""

# possible share name: ["facebook","twitter", "reddit", "linkedin", "tumblr", "weibo", "douban", "line", "pocket", "feedly", "hatena", "pinterest", "delicious", "google"]
[[share]]
  name = ""
  username = ""
[[share]]
  name = ""

[[footerLinks]]
  name = ""
  link = ""
[[footerLinks]]
  name = ""
  link = ""